# Generated by Django 6.0.4 on 2026-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='upcoming_dates',
            field=models.TextField(blank=True, help_text="Enter upcoming departure dates, e.g., 'May 20, June 5, July 12'", null=True),
        ),
    ]
